# Generated by Django 3.1.1 on 2020-09-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=10)),
                ('doctor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatientClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=5)),
                ('phone_num', models.CharField(max_length=10)),
                ('infotext', models.TextField()),
                ('participate_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='firstapp.imageclass')),
            ],
        ),
    ]
