# Generated by Django 3.1.1 on 2020-09-15 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0003_auto_20200915_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientclass',
            name='user',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
