# Generated by Django 3.1.1 on 2020-09-15 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0005_auto_20200915_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientclass',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mola', to=settings.AUTH_USER_MODEL),
        ),
    ]
