# Generated by Django 3.1.1 on 2020-09-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('phone_num', models.CharField(max_length=30)),
                ('intro_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=30)),
                ('nurse', models.CharField(max_length=30)),
                ('doctor', models.CharField(max_length=30)),
                ('patient_num', models.IntegerField()),
            ],
        ),
    ]
