# Generated by Django 3.1.1 on 2020-09-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_patient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_num',
            field=models.IntegerField(default=False),
        ),
    ]
